/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.chelonix.dagger.demo;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class AppTest {
    @Test void website_is_fetched() throws Exception {
        //
        String actual = App.fetchWebsite();
        assertThat(actual).contains("Dagger.io - CI/CD as Code that Runs Anywhere");
    }
}
